### PR TITLE
[fix] License

### PR DESCRIPTION
**Pull request by zamentur**
Here are info about license
https://emby.media/terms.html

### CODE REVIEW

**Comment by liberodark** [comment]
Sorry but is not good pr :(

**Comment by liberodark** [comment]
this part of emby is open sourced in GPL 3

**Comment by maniackcrudelis** [comment]
I agree that Emby server has a free license -> https://github.com/MediaBrowser/Emby/blob/master/LICENSE.md
But, things aren't that easy... https://emby.media/community/index.php?/topic/49862-source-code-license/
This app isn't free...

**Comment by liberodark** [comment]
for me is free have merge

**Pull request merged**
